### PR TITLE
Close picker if clicked outside

### PR DESCRIPTION
**Pull request by troggy**

### CODE REVIEW

**Comment by IonicaBizau** [comment]
:+1: 

Before merging, there are two things to fix:
- let's make an option for it, maybe some of the users don't want to close the popup when clicking outside
- check if the event target is child of the popup (currently if you click the gray area, between color circles, it will close it)

Nice work, thanks! :sparkles:

**Comment by troggy** [comment]
Done. 

> check if the event target is child of the popup

I've gone the other way: I'm checking we are not clicking color picker element in addition to `open` element. This allows color picker and `open` element to have different parents

**Comment by IonicaBizau** [comment]
@troggy Amazing! :sparkles:

**Comment by IonicaBizau** [comment]
@troggy Thanks once again. Landed in `1.2.0`. :ship: :tada:

**Pull request merged**
